export const NATIONALITIES_OPTIONS = [
	{ label: "🇦🇫 Afghanistan", value: "afghan" },
	{ label: "🇦🇱 Albania", value: "albanian" },
	{ label: "🇩🇿 Algeria", value: "algerian" },
	{ label: "🇺🇸 American", value: "american" },
	{ label: "🇦🇩 Andorra", value: "andorran" },
	{ label: "🇦🇴 Angola", value: "angolan" },
	{ label: "🇦🇷 Argentina", value: "argentine" },
	{ label: "🇦🇲 Armenia", value: "armenian" },
	{ label: "🇦🇺 Australia", value: "australian" },
	{ label: "🇦🇹 Austria", value: "austrian" },
	{ label: "🇦🇿 Azerbaijan", value: "azerbaijani" },
	{ label: "🇧🇸 Bahamas", value: "bahamian" },
	{ label: "🇧🇭 Bahrain", value: "bahraini" },
	{ label: "🇧🇩 Bangladesh", value: "bangladeshi" },
	{ label: "🇧🇧 Barbados", value: "barbadian" },
	{ label: "🇧🇾 Belarus", value: "belarusian" },
	{ label: "🇧🇪 Belgium", value: "belgian" },
	{ label: "🇧🇿 Belize", value: "belizean" },
	{ label: "🇧🇯 Benin", value: "beninese" },
	{ label: "🇧🇹 Bhutan", value: "bhutanese" },
	{ label: "🇧🇴 Bolivia", value: "bolivian" },
	{ label: "🇧🇦 Bosnia", value: "bosnian" },
	{ label: "🇧🇼 Botswana", value: "botswanan" },
	{ label: "🇧🇷 Brazil", value: "brazilian" },
	{ label: "🇬🇧 Britain", value: "british" },
	{ label: "🇧🇳 Brunei", value: "bruneian" },
	{ label: "🇧🇬 Bulgaria", value: "bulgarian" },
	{ label: "🇧🇫 Burkina", value: "burkinabe" },
	{ label: "🇲🇲 Burma", value: "burmese" },
	{ label: "🇧🇮 Burundi", value: "burundian" },
	{ label: "🇰🇭 Cambodia", value: "cambodian" },
	{ label: "🇨🇲 Cameroon", value: "cameroonian" },
	{ label: "🇨🇦 Canada", value: "canadian" },
	{ label: "🇨🇻 Cape Verde", value: "capeverdean" },
	{ label: "🇨🇫 Central African", value: "centralafrican" },
	{ label: "🇹🇩 Chad", value: "chadian" },
	{ label: "🇨🇱 Chile", value: "chilean" },
	{ label: "🇨🇳 China", value: "chinese" },
	{ label: "🇨🇴 Colombia", value: "colombian" },
	{ label: "🇰🇲 Comoros", value: "comoran" },
	{ label: "🇨🇬 Congo", value: "congolese" },
	{ label: "🇨🇷 Costa Rica", value: "costarican" },
	{ label: "🇭🇷 Croatia", value: "croatian" },
	{ label: "🇨🇺 Cuba", value: "cuban" },
	{ label: "🇨🇾 Cyprus", value: "cypriot" },
	{ label: "🇨🇿 Czech Republic", value: "czech" },
	{ label: "🇩🇰 Denmark", value: "danish" },
	{ label: "🇩🇯 Djibouti", value: "djiboutian" },
	{ label: "🇩🇴 Dominican", value: "dominican" },
	{ label: "🇪🇨 Ecuador", value: "ecuadorian" },
	{ label: "🇪🇬 Egypt", value: "egyptian" },
	{ label: "🇸🇻 El Salvador", value: "salvadoran" },
	{ label: "🇬🇶 Equatorial Guinea", value: "equatorialguinean" },
	{ label: "🇪🇷 Eritrea", value: "eritrean" },
	{ label: "🇪🇪 Estonia", value: "estonian" },
	{ label: "🇪🇹 Ethiopia", value: "ethiopian" },
	{ label: "🇫🇯 Fiji", value: "fijian" },
	{ label: "🇫🇮 Finland", value: "finnish" },
	{ label: "🇫🇷 France", value: "french" },
	{ label: "🇬🇦 Gabon", value: "gabonese" },
	{ label: "🇬🇲 Gambia", value: "gambian" },
	{ label: "🇬🇪 Georgia", value: "georgian" },
	{ label: "🇩🇪 Germany", value: "german" },
	{ label: "🇬🇭 Ghana", value: "ghanaian" },
	{ label: "🇬🇷 Greece", value: "greek" },
	{ label: "🇬🇩 Grenada", value: "grenadian" },
	{ label: "🇬🇹 Guatemala", value: "guatemalan" },
	{ label: "🇬🇳 Guinea", value: "guinean" },
	{ label: "🇬🇼 Guinea-Bissau", value: "guinea-bissauan" },
	{ label: "🇬🇾 Guyana", value: "guyanese" },
	{ label: "🇭🇹 Haiti", value: "haitian" },
	{ label: "🇭🇳 Honduras", value: "honduran" },
	{ label: "🇭🇺 Hungary", value: "hungarian" },
	{ label: "🇮🇸 Iceland", value: "icelandic" },
	{ label: "🇮🇳 India", value: "indian" },
	{ label: "🇮🇩 Indonesia", value: "indonesian" },
	{ label: "🇮🇷 Iran", value: "iranian" },
	{ label: "🇮🇶 Iraq", value: "iraqi" },
	{ label: "🇮🇪 Ireland", value: "irish" },
	{ label: "🇮🇱 Israel", value: "israeli" },
	{ label: "🇮🇹 Italy", value: "italian" },
	{ label: "🇯🇲 Jamaica", value: "jamaican" },
	{ label: "🇯🇵 Japan", value: "japanese" },
	{ label: "🇯🇴 Jordan", value: "jordanian" },
	{ label: "🇰🇿 Kazakhstan", value: "kazakhstani" },
	{ label: "🇰🇪 Kenya", value: "kenyan" },
	{ label: "🇰🇮 Kiribati", value: "kiribatian" },
	{ label: "🇰🇵 Korea", value: "korean" },
	{ label: "🇽🇰 Kosovo", value: "kosovar" },
	{ label: "🇰🇼 Kuwait", value: "kuwaiti" },
	{ label: "🇰🇬 Kyrgyzstan", value: "kyrgyzstani" },
	{ label: "🇱🇦 Laos", value: "laotian" },
	{ label: "🇱🇻 Latvia", value: "latvian" },
	{ label: "🇱🇧 Lebanon", value: "lebanese" },
	{ label: "🇱🇸 Lesotho", value: "lesothoan" },
	{ label: "🇱🇷 Liberia", value: "liberian" },
	{ label: "🇱🇾 Libya", value: "libyan" },
	{ label: "🇱🇮 Liechtenstein", value: "liechtensteiner" },
	{ label: "🇱🇹 Lithuania", value: "lithuanian" },
	{ label: "🇱🇺 Luxembourg", value: "luxembourger" },
	{ label: "🇲🇰 Macedonia", value: "macedonian" },
	{ label: "🇲🇬 Madagascar", value: "malagasy" },
	{ label: "🇲🇼 Malawi", value: "malawian" },
	{ label: "🇲🇾 Malaysia", value: "malaysian" },
	{ label: "🇲🇻 Maldives", value: "maldivian" },
	{ label: "🇲🇱 Mali", value: "malian" },
	{ label: "🇲🇹 Malta", value: "maltese" },
	{ label: "🇲🇭 Marshall Islands", value: "marshallese" },
	{ label: "🇲🇷 Mauritania", value: "mauritanian" },
	{ label: "🇲🇺 Mauritius", value: "mauritian" },
	{ label: "🇲🇽 Mexico", value: "mexican" },
	{ label: "🇫🇲 Micronesia", value: "micronesian" },
	{ label: "🇲🇩 Moldova", value: "moldovan" },
	{ label: "🇲🇨 Monaco", value: "monacan" },
	{ label: "🇲🇳 Mongolia", value: "mongolian" },
	{ label: "🇲🇪 Montenegro", value: "montenegrin" },
	{ label: "🇲🇦 Morocco", value: "moroccan" },
	{ label: "🇲🇿 Mozambique", value: "mozambican" },
	{ label: "🇲🇲 Myanmar", value: "myanmarese" },
	{ label: "🇳🇦 Namibia", value: "namibian" },
	{ label: "🇳🇷 Nauru", value: "nauruan" },
	{ label: "🇳🇵 Nepal", value: "nepalese" },
	{ label: "🇳🇱 Netherlands", value: "dutch" },
	{ label: "🇳🇿 New Zealand", value: "newzealander" },
	{ label: "🇳🇮 Nicaragua", value: "nicaraguan" },
	{ label: "🇳🇪 Niger", value: "nigerien" },
	{ label: "🇳🇬 Nigeria", value: "nigerian" },
	{ label: "🇳🇴 Norway", value: "norwegian" },
	{ label: "🇴🇲 Oman", value: "omani" },
	{ label: "🇵🇰 Pakistan", value: "pakistani" },
	{ label: "🇵🇼 Palau", value: "palauan" },
	{ label: "🇵🇸 Palestine", value: "palestinian" },
	{ label: "🇵🇦 Panama", value: "panamanian" },
	{ label: "🇵🇬 Papua New Guinea", value: "papuanewguinean" },
	{ label: "🇵🇾 Paraguay", value: "paraguayan" },
	{ label: "🇵🇪 Peru", value: "peruvian" },
	{ label: "🇵🇭 Philippines", value: "filipino" },
	{ label: "🇵🇱 Poland", value: "polish" },
	{ label: "🇵🇹 Portugal", value: "portuguese" },
	{ label: "🇶🇦 Qatar", value: "qatari" },
	{ label: "🇷🇴 Romania", value: "romanian" },
	{ label: "🇷🇺 Russia", value: "russian" },
	{ label: "🇷🇼 Rwanda", value: "rwandan" },
	{ label: "🇰🇳 Saint Kitts and Nevis", value: "saintkittsandnevisian" },
	{ label: "🇱🇨 Saint Lucia", value: "saintlucian" },
	{ label: "🇻🇨 Saint Vincent and the Grenadines", value: "saintvincentian" },
	{ label: "🇼🇸 Samoa", value: "samoan" },
	{ label: "🇸🇲 San Marino", value: "sanmarinese" },
	{ label: "🇸🇹 Sao Tome and Principe", value: "saotomean" },
	{ label: "🇸🇦 Saudi Arabia", value: "saudiarabian" },
	{ label: "🇸🇳 Senegal", value: "senegalese" },
	{ label: "🇷🇸 Serbia", value: "serbian" },
	{ label: "🇸🇨 Seychelles", value: "seychellois" },
	{ label: "🇸🇱 Sierra Leone", value: "sierraleonean" },
	{ label: "🇸🇬 Singapore", value: "singaporean" },
	{ label: "🇸🇰 Slovakia", value: "slovakian" },
	{ label: "🇸🇮 Slovenia", value: "slovenian" },
	{ label: "🇸🇧 Solomon Islands", value: "solomonislander" },
	{ label: "🇸🇴 Somalia", value: "somali" },
	{ label: "🇿🇦 South Africa", value: "southafrican" },
	{ label: "🇸🇸 South Sudan", value: "southsudanese" },
	{ label: "🇪🇸 Spain", value: "spanish" },
	{ label: "🇱🇰 Sri Lanka", value: "srilankan" },
	{ label: "🇸🇩 Sudan", value: "sudanese" },
	{ label: "🇸🇷 Suriname", value: "surinamese" },
	{ label: "🇸🇿 Swaziland", value: "swazi" },
	{ label: "🇸🇪 Sweden", value: "swedish" },
	{ label: "🇨🇭 Switzerland", value: "swiss" },
	{ label: "🇸🇾 Syria", value: "syrian" },
	{ label: "🇹🇼 Taiwan", value: "taiwanese" },
	{ label: "🇹🇯 Tajikistan", value: "tajikistani" },
	{ label: "🇹🇿 Tanzania", value: "tanzanian" },
	{ label: "🇹🇭 Thailand", value: "thai" },
	{ label: "🇹🇱 Timor-Leste", value: "timorese" },
	{ label: "🇹🇬 Togo", value: "togolese" },
	{ label: "🇹🇴 Tonga", value: "tongan" },
	{ label: "🇹🇹 Trinidad and Tobago", value: "trinidadian" },
	{ label: "🇹🇳 Tunisia", value: "tunisian" },
	{ label: "🇹🇷 Turkey", value: "turkish" },
	{ label: "🇹🇲 Turkmenistan", value: "turkmen" },
	{ label: "🇹🇻 Tuvalu", value: "tuvaluan" },
	{ label: "🇺🇬 Uganda", value: "ugandan" },
	{ label: "🇺🇦 Ukraine", value: "ukrainian" },
	{ label: "🇦🇪 United Arab Emirates", value: "emirian" },
	{ label: "🇬🇧 United Kingdom", value: "british" },
	{ label: "🇺🇸 United States", value: "american" },
	{ label: "🇺🇾 Uruguay", value: "uruguayan" },
	{ label: "🇺🇿 Uzbekistan", value: "uzbekistani" },
	{ label: "🇻🇺 Vanuatu", value: "ni-vanuatu" },
	{ label: "🇻🇦 Vatican City (Holy See)", value: "vatican" },
	{ label: "🇻🇪 Venezuela", value: "venezuelan" },
	{ label: "🇻🇳 Vietnam", value: "vietnamese" },
	{ label: "🇾🇪 Yemen", value: "yemeni" },
	{ label: "🇿🇲 Zambia", value: "zambian" },
	{ label: "🇿🇼 Zimbabwe", value: "zimbabwean" },
];
